#~/.bash_aliases
alias clean='sudo apt-get autoclean; sudo apt-get autoremove'
alias update='sudo apt-get update; sudo apt-get upgrade -y'
alias minecraft='java -jar ~/Programs/Games/Minecraft/Minecraft.jar'
alias urbanterror='bash ~/Documents/config/shortcuts/urbanTerror.sh' 
alias casalomount='bash ~/Documents/config/shortcuts/casaloMount.sh'
alias cp='cp -r'
alias rm='rm -r'
alias youplay='bash ~/Documents/config/shortcuts/youPlay.sh $@'
alias youplayvideo='bash ~/Documents/config/shortcuts/youPlayVideo.sh $@'
alias shutdown='sudo poweroff'
alias vcp='vcp -R'
alias killall='killall -9'
alias Mint='cd $MINT'
alias mount='sudo mount -o umask=0'
alias umount='sudo umount'
alias dus='du -sh * | sort -k1,1rh'
alias screenfetch='bash ~/Documents/source/screenfetch/screenfetch-dev'
alias logcat='python ~/Documents/source/colored-adb-logcat/colored-adb-logcat.py'
alias MintBackup='bash ~/Documents/config/shortcuts/mintBackup.sh'
alias wiki='bash ~/Documents/config/shortcuts/wikisole.sh'
alias startup='bash ~/Documents/config/shortcuts/startup.sh'
alias bolderlomount='bash ~/Documents/config/shortcuts/remoteMount.sh'
alias restartTeamviewer='bash ~/Documents/config/shortcuts/restartTeamviewer.sh'
alias runDevEnv='bash ~/Documents/config/shortcuts/runDevEnv.sh'
alias connectJmb='bash ~/Documents/config/shortcuts/connectJmb.sh'
alias log='bash ~/Documents/config/shortcuts/log.sh'
alias touchpad='bash ~/Documents/config/shortcuts/toggleTouchpad.sh $@'
