#alias iron='sh ~/Documents/.Shortcuts/Iron.sh'
alias clean='sudo apt-get autoclean; sudo apt-get autoremove'
alias update='sudo apt-get update; sudo apt-get upgrade -y; sudo youtube-dl -U'
alias minecraft='java -jar ~/Programs/Games/Minecraft/Minecraft.jar'
alias urbanterror='sh ~/Documents/.Shortcuts/UrbanTerror.sh' 
alias casalomount='bash ~/Documents/.Shortcuts/casaloMount.sh'
alias cp='cp -r'
alias rm='rm -r'
alias youplay='sh ~/Documents/.Shortcuts/YouPlay.sh'
alias youplayvideo='sh ~/Documents/.Shortcuts/YouPlayVideo.sh $1'
alias shutdown='sudo poweroff'
#alias uxterm='uxterm -bg black -fg green'
#alias uxterm='tabbed -c uxterm -bg black -fg green -fn terminus-12 -into'
#alias cpv='cat $1 |pv -s 100g -p -e -r > $2'
alias vcp='vcp -R'
alias killall='killall -9'
alias tarp='tar -I pbzip2 $1 $2 $3'
alias KUL='cd $KUL'
alias mount='sudo mount'
alias umount='sudo umount'
alias dus='du -sh * | sort -k1,1rh'
alias screenfetch='sh ~/Documents/.Shortcuts/ScreenFetch.sh'
alias logcat='python ~/Documents/.Shortcuts/colored-adb-logcat/colored-adb-logcat.py'
alias KULBackup='sh ~/Documents/.Shortcuts/KulBackup.sh'
alias h5cc='sh /home/evert/Documents/KULeuven/NEW_2013_07_15/HDF5/hdf5-1.8.11/tools/misc/h5cc'
#alias hdfview='sh /home/evert/Documents/KULeuven/NEW_2013_07_15/HDF5/hdf-java/hdf-java/bin/hdfview.sh'
alias hdfview='cd /home/evert/Documents/KULeuven/NEW_2013_07_15/HDF5/hdf-java/hdf-java/bin; sh hdfview.sh'
function mkdircd() {
	mkdir $@; 
	cd $@;
}
